repos:
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: poetry run mypy --strict
    language: system
    files: ^app/.*\.py$
    types: [python]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.13.1'
  hooks:
    - id: ruff-check
    - id: ruff-format

- repo: local
  hooks:
  - id: integration-tests
    name: integration-tests
    entry: poetry run pytest tests/backend/integration
    language: system
    pass_filenames: false
    always_run: true