repos:
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: poetry run mypy
    language: system
    files: ^app/.*\.py$
    types: [python]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.13.1'
  hooks:
    - id: ruff-check
    - id: ruff-format