name: CI Flow

on: push

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - name: Set up Python 3.12
      uses: actions/setup-python
      with:
        python-version: "3.12"
    - name: Set up environment
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry shell
    - name: Announce Start
      run: echo "Starting CI Flow"
    - name: Run mypy strict
      run: mypy --strict --config-file=pyproject.toml
    - name: Run linter
      run: ruff check --config-file=pyproject.toml
    - name: Run formatter
      run: ruff format --config-file=pyproject.toml