name: CI Flow

on: push

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Set up environment
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Announce Start
      run: echo "Starting CI Flow"
    - name: Run mypy strict
      run: poetry run mypy app/**/*.py --strict
    - name: Run linter
      run: poetry run ruff check
    - name: Run formatter
      run: poetry run ruff format --check